version: '2'
services:

  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:mypass@postgres:5432/postgres

  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_PASSWORD: mypass
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  nginx:
        restart: always
        build:
            context: .
        image: docknginx
        container_name: nginx-proxy
        hostname: nginx
        ports:
            - "80:80" 
        depends_on:
            - web
        networks:
            - secured_web_app_default
        tty: true

networks:
  secured_web_app_default:
    external: true
